[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.188"
futures = "0.3.28"
tokio = {version = "1.32.0", features = ["full"]}
crossterm = "0.27"
reqwest = "0.12.12"
serde_json = "1.0"
rand = "0.9"

[dependencies.mongodb]
version = "3.2.0"